# Generated by Django 6.0.7 on 2026-08-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ValoresCalculadora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(unique=True)),
                (
                    "valor_retencion",
                    models.DecimalField(
                        decimal_places=2, max_digits=2, verbose_name="Valor Retención"
                    ),
                ),
                (
                    "valor_iva",
                    models.DecimalField(
                        decimal_places=2, max_digits=2, verbose_name="Valor IVA"
                    ),
                ),
                (
                    "valor_ppm",
                    models.DecimalField(
                        decimal_places=2, max_digits=2, verbose_name="Valor PPM"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ValoresFinancieros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(unique=True)),
                (
                    "valor_uf",
                    models.DecimalField(
                        decimal_places=2, max_digits=2, verbose_name="Valor UF"
                    ),
                ),
                (
                    "valor_utm",
                    models.DecimalField(
                        decimal_places=2, max_digits=2, verbose_name="Valor UTM"
                    ),
                ),
                (
                    "dolar_observado",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=2,
                        verbose_name="Valor Dólar Observado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiciosBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_servicio",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="ID del servicio"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="Nombre del servicio"
                    ),
                ),
                (
                    "semanas_base",
                    models.IntegerField(verbose_name="Semanas base del servicio"),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("semanas_base__gte", 1)),
                        name="check_minimo_semanas_base",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("semanas_base__lte", 60)),
                        name="check_maximo_semanas_base",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiciosExtra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_servicio",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="ID del servicio extra"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=40,
                        unique=True,
                        verbose_name="Nombre del servicio extra",
                    ),
                ),
                (
                    "semanas_penalizacion",
                    models.IntegerField(verbose_name="Semanas de Penalización"),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("semanas_penalizacion__gte", 1)),
                        name="check_minimo_semanas_penalizacion",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("semanas_penalizacion__lte", 60)),
                        name="check_maximo_semanas_penalizacion",
                    ),
                ],
            },
        ),
    ]
