# Generated by Django 6.0.7 on 2026-08-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="valoresfinancieros",
            name="dolar_observado",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Valor Dólar Observado"
            ),
        ),
        migrations.AlterField(
            model_name="valoresfinancieros",
            name="valor_uf",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Valor UF"
            ),
        ),
        migrations.AlterField(
            model_name="valoresfinancieros",
            name="valor_utm",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Valor UTM"
            ),
        ),
    ]
