# Generated by Django 6.0.7 on 2026-09-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_valoresfinancieros_dolar_observado_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="USMUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pin", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("checked", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="serviciosbase",
            name="check_minimo_semanas_base",
        ),
        migrations.RemoveConstraint(
            model_name="serviciosbase",
            name="check_maximo_semanas_base",
        ),
        migrations.DeleteModel(
            name="ServiciosBase",
        ),
        migrations.RemoveConstraint(
            model_name="serviciosextra",
            name="check_minimo_semanas_penalizacion",
        ),
        migrations.RemoveConstraint(
            model_name="serviciosextra",
            name="check_maximo_semanas_penalizacion",
        ),
        migrations.DeleteModel(
            name="ServiciosExtra",
        ),
        migrations.DeleteModel(
            name="ValoresCalculadora",
        ),
        migrations.DeleteModel(
            name="ValoresFinancieros",
        ),
    ]
