# Generated by Django 6.1 on 2026-09-11 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_usmuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Proyecto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('generation', models.IntegerField(verbose_name='Generación (Año)')),
                ('members', models.TextField(help_text='Nombres separados por comas o saltos de línea', verbose_name='Integrantes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proyecto Inicial',
                'verbose_name_plural': 'Proyectos Iniciales',
                'ordering': ['-generation', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='initial_projects/', verbose_name='Imagen')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de aparición')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.initialproject', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Imagen de Proyecto',
                'verbose_name_plural': 'Imágenes de Proyecto',
                'ordering': ['order'],
            },
        ),
    ]
