# Generated by Django 6.0.7 on 2026-09-11 22:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_initialproject_projectimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nombre Completo"),
                ),
                (
                    "generation",
                    models.IntegerField(
                        db_index=True,
                        validators=[
                            django.core.validators.MinValueValidator(1990),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Generación (Año de Egreso)",
                    ),
                ),
                ("bio", models.TextField(verbose_name="Biografía")),
                (
                    "current_role",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Rol o Cargo Actual"
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True, max_length=255, verbose_name="LinkedIn"
                    ),
                ),
                (
                    "github_url",
                    models.URLField(blank=True, max_length=255, verbose_name="GitHub"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo de Contacto"
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="community/profile_pics/",
                        verbose_name="Foto de Perfil",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Miembro de la Comunidad",
                "verbose_name_plural": "Comunidad y Exalumnos",
                "ordering": ["-generation", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Título del Taller"),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "year",
                    models.IntegerField(
                        db_index=True,
                        validators=[
                            django.core.validators.MinValueValidator(1990),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Año de Realización",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("taller", "Taller"),
                            ("charla", "Charla"),
                            ("conferencia", "Conferencia"),
                            ("hackathon", "Hackathon"),
                            ("otro", "Otro"),
                        ],
                        default="taller",
                        max_length=50,
                        verbose_name="Tipo de Evento",
                    ),
                ),
                (
                    "guia_url",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="URL Guía Escrita",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Taller Telemático",
                "verbose_name_plural": "Talleres Telemáticos",
                "ordering": ["-year", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="WorkshopImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="workshops/", verbose_name="Fotografía"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Orden de aparición"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Leyenda"
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="dashboard.workshop",
                        verbose_name="Taller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fotografía de Taller",
                "verbose_name_plural": "Fotografías de Taller",
                "ordering": ["order", "id"],
            },
        ),
    ]
