# Generated by Django 6.1 on 2026-09-11 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_communitymember_workshop_workshopimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialproject',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='initialproject',
            name='generation',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Generación (Año)'),
        ),
        migrations.AlterField(
            model_name='initialproject',
            name='members',
            field=models.TextField(help_text='Nombres separados por comas o saltos de línea', validators=[django.core.validators.MaxLengthValidator(150)], verbose_name='Integrantes'),
        ),
        migrations.AlterField(
            model_name='initialproject',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título del Proyecto'),
        ),
    ]
