# Generated by Django 6.0.7 on 2026-09-12 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_alter_initialproject_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="initialproject",
            options={
                "ordering": ["-generation", "-created_at"],
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
            },
        ),
    ]
