upstream django_upstream {
    server web-django:8000;
}

server {
    listen 80;
    server_name telematica.josnic.cl;

    # Tamaño máximo de subida para el buzón (2GB)
    client_max_body_size 2G;

    # =======================================================
    # 1. LANDING PAGE (/)
    # =======================================================
    location / {
        root /var/www/landing;
        index index.html;
        try_files $uri $uri/ =404;
    }

    # =======================================================
    # 2. (ELIMINADO: DOCMOST WIKI)
    # =======================================================

    # =======================================================
    # 2. (ELIMINADO: SITIO QUARTZ)
    # =======================================================

    # =======================================================
    # 3. ARCHIVOS PESADOS (/recursos/) - Optimizado
    # =======================================================
    location /recursos/ {
        alias /var/www/recursos/;
	autoindex on;
	add_header Content-Security-Policy "frame-ancestors 'self' https://diftel.josnic.cl;" always;
        
        # Rendimiento de kernel para archivos grandes
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        send_timeout 300s;

        # Cabeceras para permitir reanudar descargas cortadas
        add_header Accept-Ranges bytes;
    }

    # =======================================================
    # 4. FRONTEND BUZÓN (/buzon/)
    # =======================================================
    location /buzon/ {
        alias /var/www/landing/buzon/;
        index index.html;
        try_files $uri $uri/ /buzon/index.html;
    }

    # =======================================================
    # 5. API DJANGO (/buzon/api/ y /admin/)
    # =======================================================
    location ~ ^/(buzon/api|admin) {
        proxy_pass http://django_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Timeouts amplios para subidas de archivos grandes
        proxy_connect_timeout 300s;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }

    # Archivos estáticos propios de Django (Admin styles)
    location /static/ {
        alias /var/www/django_static/;
    }
}
